
### CNNC: convolutional neural network for coexpression {#CNNC}

CNNC [@RN174]<!--[113]--> is proposed to infer causal interactions between genes from scRNA-seq data. 

*Model.* CNNC is a Convolutional Neural Network (CNN, Fig.\@ref(fig:Figure4)F), the most popular DL model. CNNC takes expression levels of two genes from many cells and transforms them into a 32 x 32 image-like normalized empirical probability function (NEPDF), which measures the probabilities of observing different coexpression levels between the two genes. CNNC includes 6 convolutional layers, 3 maxpooling layers, 1 flatten layer, and one output layer. All convolution layers have 32 kernels of  size 3x3.  Depending on the application, the output layer can be designed to predict the state of interaction (Yes/No) between the genes or the causal interaction between the input genes (no interaction, gene A regulates gene B, or gene B regulates gene A). 

*Evaluation matrics.* Prediction AUROC, AUPRC, and accuracy were assessed. 

*Result.* CNNC was trained to predict transcription factor (TF)-Gene interactions using the mESC data from scQuery [@RN195]<!--[114]-->, where the ground truth interactions were obtained from the ChIP-seq dataset from the GTRD database [@RN196]<!--[115]-->. The performance was compared with DNN, count statistics [@RN197]<!--[116]-->, and mutual information-based approach [@RN178]<!--[117]-->.  CNNC was shown to have more than 20% higher AUPRC than other methods and reported almost no false-negative for the top 5% predictions. CNNC was also trained to predict the pathway regulator-target gene pairs. The positive regulator-gene pairs were obtained from KEGG [@RN198]<!--[118]-->, Reactome [@RN176]<!--[119]-->, and negative samples were genes pairs that appeared in pathways but not interacted. CNNC was shown to have better performance of predicting regulator-gene pairs on both KEGG and Reactome pathways than other methods including Pearson correlation, count statistics, GENIE3 [@RN199]<!--[120]-->, Mutual information, Bayesian directed network (BDN), and DREMI [@RN178]<!--[117]-->.  CNNC was also applied for causality prediction between two genes, that is if two genes regulate each other and if they do, which gene is the regulator. The ground truth causal relationships were also obtained from the KEGG and Reactome datasets. Again, CNNC reported better performance than BDN, the common method developed to learn casual relationshop from gene expression data. CNNC was finally trained to assign 3 essential cell functions (cell cycle, circadian rhythm, and immune system) to genes. This is achieved by training CNNC to predict pair of genes from same function (e.g. Cell Cycle defined by mSigDB from gene set enrichment analysis (GSEA [@RN200]<!--[121]-->) as 1 and all other pairs as 0. The performance was compared with “guilt by association” and DNN, and CNNC were shown to have more than 4% higher AUROC and reported all positives for the top 10% predictions. 
