

# Table2b

Title=c("68k PBMCs",
        "Human pluripotent",
        "CITE-seq",
        "Midbrain and Dopaminergic Neuron Development",
        "HCA",
        "Breast tumor",
        "293T cells",
        "Jurkat",
        "ESC, Time-course",
        "Baron-Hum-1",
        "Baron-Hum-2",
        "Camp",
        "CEL-seq2",
        "Darmanis",
        "Tirosh-brain",
        "Patel",
        "Li",
        "Tirosh-skin",
        "xenograft 3, and 4",
        "Petropoulos",
        "Pollen",
        "Xin",
        "Yan",
        "PBMC3k",
        "CyTOF, Dengue",
        "CyTOF, ccRCC",
        "CyTOF, breast",
        "Chung, BC",
        "Li, CRC",
        "Pancreatic datasets",
        "Kang, PBMC"
        )

Algorithm=c("DCA, SAVER-X, LATE, scVAE, scDeepCluster, scCapsNet, scDGN",
            "DCA",
            "SAVER-X",
            "SAVER-X",
            "SAVER-X",
            "SAVER-X",
            "DeepImpute, iMAP", 
            "DeepImpute, iMAP",
            "scGAN",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "PERMUDA, DESC",
            "scGMAI, sclGAN, VASC",
            "Dhaka, scvis",
            "Dhaka",
            "scGMAI, VASC",
            "scvis",
            "Dhaka",
            "VASC/netAE",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "VASC, scVI",
            "SAUCIE",
            "SAUCIE",
            "SAUCIE",
            "DigitalDLSorter",
            "DigitalDLSorter",
            "scDGN",
            "scGen"
            )

Cell_Origin=c("Blood",
               "hESCs",
               "Cord blood mononuclear cells",
               "Brain/ embryo ventral midbrain cells",
               "Immune cell, Human Cell Atlas",
               "Immune cell in tumor micro-environment",
               "Embryonic kidney",
               "Blood/ lymphocyte",
               "ESC",
               "Pancreatic islets",
               "Pancreatic islets",
               "Liver cells",
               "Pancreas/Islets of Langerhans",
               "Brain/cortex",
               "Oligodendroglioma",
               "Primary glioblastoma cells",
               "Blood",
               "melanoma",
               "Breast tumor",
               "Human embryos",
               "",
               "Pancreatic cells (α-, β-, δ-)",
               "embryonic stem cells",
               "Blood",
               "Dengue infection",
               "Immunue profile of 73 ccRCC patients",
               "3 patients",
               "Breast tumor",
               "Colorectal cancer",
               "Pancreas",
               "PBMC stimulated by INF-β"
               )

Number_of_Cells=c("68,579",
                  "1,876",
                  "8,005",
                  "1,977",
                  "500,000",
                  "45,000",
                  "13,480",
                  "3,200",
                  "350,758",
                  "1,937",
                  "1,724",
                  "303",
                  "",
                  "466",
                  ">4,800",
                  "875",
                  "561",
                  "4,645",
                  "~250",
                  "1,529",
                  "348",
                  "1,600",
                  "124",
                  "2,700",
                  "11 M, ~42 antibodies", 
                  "3.5 M, ~40 antibodies",
                  "",
                  "515",
                  "2,591",
                  "14,693",
                  "~15,000")

Data_Sources=c("10X Single Cell Gene Expression Datasets",
               "GSE102176",
               "GSE100866",
               "GSE76381",
               "HCA data portal",
               "GSE114725",
               "10X Single Cell Gene Expression Datasets",
               "10X Single Cell Gene Expression Datasets",
               "GSE75748",
               "GSM2230757",
               "GSM2230758",
               "GSE96981",
               "GSE85241",
               "GSE67835",
               "GSE70630", 
               "GSE57872",
               "GSE146974",
               "GSE72056",
               "EGAS00001002170",
               "E-MTAB-3929",
               "SRP041736",
               "GSE81608",
               "GSE36552",
               "SRP073767",
               "Cytobank, 82023",
               "Cytobank: 875",
               "Flow Repository: FR-FCM-ZYJP",
               "GSE75688",
               "GSE81861",
               "SeuratData",
               "GSE96583"
               )

Refs=c("",
       "[122]",
       "[123]",
       "[124]", 
       "",
       "[125]",
       "",
       "",
       "[126]",
       "[127]",
       "[127]",
       "[128]",
       "[129]",
       "[130]",
       "[131]", 
       "[132]",
       "[61]", 
       "[67]", 
       "[133]", 
       "",
       "[134]", 
       "[135]",
       "[136]",
       "[96]",
       "[14]",
       "[137]",
       "[125]",
       "[88]",
       "[89]",
       "",
       "[116]"
       )


table2b=data.frame(Title=Title,
                  Algorithm=Algorithm,
                  Cell_Origin=Cell_Origin,
                  Number_of_Cells=Number_of_Cells,
                  Data_Sources=Data_Sources,
                  Refs=Refs
                  )


saveRDS(table2b, "./Table/Table2b.rds")



