
### Clustering {#ch-4-1-3}

Evaluating the performance of clustering algorithms is not as trivial as counting the number of errors like supervised learning. In general, the clustering performance evaluation metric should not just take absolute corrected labelled cells  into account but also consider if the clustering defines a good similarity or separation in the dataset compared to ground truth. When ground truth is not available, evaluation must be performed using model itself such as clustering distance, dispersion, etc. Similar measures, such as Adjusted Rand Index (ARI) and Silhouette Index discussed in Section \@ref(ch.4.2.1) can also be employed here to measure the agreement between predicted assignment to the ground-truth assignment. 

**Normalized Mutual Information (NMI).** The mutual information(MI) [47]  is a measure of mutual dependency between two cluster assignments $U$ and $V$. It quantifies the amount of information we could have about one assignment by observing the other assignment. For $N$ samples, we have the entropy for cluster assignments $U$ and $V$ as

$$H(U)=\sum_{i=1}^{\vert U \vert}P_{U}(i)\log{(P_{U}(i))},  H(V)=\sum_{i=1}^{\vert V \vert}P_{V}(i)\log{(P_{V}(i))}$$

where $P_{U}(i)=\frac{\vert U_{i} \vert}{N}$ and $P_{V}(j)=\frac{\vert V_{j} \vert}{N}$. Also, define the joint distribution probability is $P_{UV}(i,j)=\frac{\vert U_{i}\cap V_{j} \vert}{N}$. Then, the mutual information of $U$ and $V$ is defined as

$$MI(U,V)=\sum_{i=1}^{\vert U \vert}\sum_{j=1}^{\vert V \vert}P_{UV}(i,j)\log{\frac{P_{UV}(i,j)}{P_{U}(i)P_{V}(j)}}$$

The NMI is a normalization of the $MI$ score between 0 and 1. For example, the average NMI is defined as [53]

$$NMI(U,V)=\frac{2 \times MI(U,V)}{[H(U) + H(V)]}$$

**Homogeneity, Completeness, and V-Measure.** The homogeneity score (HS) measures the extent to which its clusters contain only samples that belong to one cell type, or $HS=1-H(P(U\vert V))/H(P(U))$, where $H()$ is the entropy, and $U$ is the ground-truth assignment and $V$ is the predicted assignment. The $HS$ range from 0 to 1, where 1 indicates perfectly homogeneous labelling.  Similarly, the completeness score (CS) is defined as $CS=1-H(P(V \vert U))/H(P(V))$, its values range from 0 to 1, where 1 indicates all member from a ground-truth label are assigned to a single cluster.

The V-Measure [54] is the harmonic mean between $HS$ and $CS$, defined as $V_{\beta}=\frac{(1+\beta)HS×CS}{\beta HC+CS}$, where $\beta$ indicates the weight of $HS$. V-Measure is a more symmetric, i.e. switching the true and predicted cluster labels does not change V-Measure.
    
    
    
    
    
    
    
    
    
    
    
