

# Table2c

Title=c("Brain cells from E18 mice",
        "Midbrain and Dopaminergic Neuron Development",
        "Mouse cell atlas",
        "neuron9k", 
        "Mouse Visual Cortex",
        "murine epidermis",
        "myeloid progenitors",
        "Cell-cycle",
        "A single-cell survey",
        "Tabula Muris",
        "Baron-Mou-1",
        "Biase",
        "Biase",
        "Deng",
        "Klein",
        "Goolam",
        "Kolodziejczyk",
        "Usoskin",
        "Zeisel",
        "Bladder cells",
        "HEMATO",
        "retinal bipolar cells",
        "Embryo at 9 time points",
        "Embryo at 9 time points",
        "CyTOF", 
        "Solo",
        "Nestorowa",
        "small intestinal epithelium"
        )

Algorithm=c("DCA, SAUCIE",
            "SAVER-X",
            "SAVER-X",
            "DeepImpute",
            "DeepImpute",
            "DeepImpute",
            "LATE, DESC, SAUCIE",
            "sclGAN",
            "NA",
            "iMAP",
            "VASC",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "scGMAI, VASC",
            "VASC, scDeepCluster, sclGAN",
            "VASC",
            "VASC",
            "VASC",
            "VASC, scVI, SAUCIE, netAE",
            "scDeepCluster",
            "scVI",
            "scVI, scCapsNet, SAUCIE",
            "LDAVE",
            "LDAVE",
            "SAUCIE",
            "Solo",
            "netAE",
            "scGen"
            )

Cell_Origin=c("Brain Cortex",
              "Ventral Midbrain",
              "NA",
              "Cortex",
              "Brain cortex",
              "Epidermis",
              "Bone marrow",
              "mESC",
              "Intestine",
              "Mouse cells",
              "Pancreas",
              "Embryos/SMARTer",
              "Embryos/Fluidigm",
              "Liver",
              "Stem Cells",
              "Mouse Embryo",
              "mESC",
              "Lumbar",
              "Cortex, hippocampus",
              "Bladder",
              "Blood cell",
              "retinal",
              "embryos from E6.5 to E8.5",
             "embryos from E9.5 to E13.5",
              "Mouse thymus",
              "Mouse kidneys",
             "hematopoietic stem and progenitor cells",
              "Infected with Salmonella and worm H. polygyrus "
               )

Number_of_Cells=c("1,306,127",
                  "1,907",
                  "405,796",
                  "9,128",
                  "114,601",
                  "1,422",
                  "2,730",
                  "288",
                  "7,721",
                  ">100K",
                  "822",
                  "56",
                  "90",
                  "317",
                  "2,717",
                  "124",
                  "704",
                  "864",
                  "3,005",
                  "12,884",
                  ">10,000",
                  "~25,000",
                  "116,312",
                  "~2 millions",
                  "200K, ~38 antibodies",
                  "~8,000",
                  "1,920",
                  "1,957"
                  )

Data_Sources=c( "10x: Single Cell Gene Expression Datasets",
                "GSE76381",
                "GSE108097",
                "10x: Single Cell Gene Expression Datasets",
                "GSE102827",
                "GSE67602",
                "GSE72857",
                "E-MTAB-2805",
                "GSE92332",
                "NA",
                "GSM2230761",
                "GSE57249",
                "GSE59892",
                "GSE45719",
                "GSE65525",
                "E-METAB-3321",
                "E-MTAB-2600",
                "GSE59739",
                "GSE60361",
                "GSE129845",
                "GSE89754",
                "GSE81905",
                "GSE87038",
                "GSE119945",
                "Cytobank: 52942", 
                "GSE140262",
                "GSE81682",
                "GSE92332"
               )

Refs=c("",
       "[@RN137]",
       "[@RN224]",
       "",
       "[@RN225]",
       "[@RN227]",
       "[@RN228]",
       "[@RN229]",
       "[@RN226]",
       "",
       "[@RN210]",
       "[@RN230]",
       "[@RN230]",
       "[@RN211]",
       "[@RN239]",
       "[@RN237]",
       "[@RN238]",
       "[@RN241]",
       "[@RN240]",
       "[@RN210]",
       "[@RN234]",
       "[@RN163]",
       "[@RN233]",
       "[@RN232]",
       "[@RN236]",
       "[@RN154]",
       "[@RN235]",
       "[@RN226]"
       )


table2c=data.frame(Title=Title,
                  Algorithm=Algorithm,
                  Cell_Origin=Cell_Origin,
                  Number_of_Cells=Number_of_Cells,
                  Data_Sources=Data_Sources,
                  Refs=Refs
                  )


saveRDS(table2c, "./Table/Table2c.rds")



